init_options = {
    format = {
        enable = true, -- to use lsp format

    },
    scan_cmake_in_package = false, -- it will deeply check the cmake file which found when search cmake packages.
    semantic_token = false,
}

